### ISSUE TITLE
useImageGet.jsxについて

### ISSUE THREAD

**Issue by reachscript-jak** [macmeals/todo_react_app3#7]
https://github.com/macmeals/todo_react_app3/blob/6bc8609c4bef51fde72682a25a691942fc09b3e1/src/hook/useImageGet.jsx#L10-L13

以下気になった点です！

- hooksはコンポーネントを持たないので拡張子はjsでOKです
- StateにuseImageという名称をつけていますがカスタムフックと混同するのでuse~はカスタムフック名だけにしておくと良いです
- このフックの役割は画像パスを取得することだと思うので、Stateにresponseを全て持たせるのではなく、対象の画像のパスのみこのカスタムフック内で取り出してStateに設定しreturnしてあげたほうが良いです（コンポーネント側はカスタムフックから返却されたSateをurlに設定するだけで良くなる）

※上記、名称や拡張子等は他のカスタムフックに関しても同様です

**Comment by reachscript-jak** [comment]
名称に関しては以下のみずさんのissueと重複してますね🙏
https://github.com/macmeals/todo_react_app_4/issues/3

**Comment by macmeals** [comment]
・hooksの拡張子はjsにしました。
・Stateにuse〜としているものは全てリネームしました。
　例：apiPokemonfront, setApiPokemonfront

・useImageGet.jsは画像のURLを渡すHookに書き換えました。合わせてuseTextGet.jsの方もタイトルを渡すHookに書き換えています。
（ご指摘の意味としては、「Hook内で加工できる値は全て加工した上で、ページ系のコンポーネントに渡す。ページ系のコンポーネントはただ、その値を表示するだけ」という意味合いかと思いましたので、両方ともにそれを適応しました。）

**Comment by macmeals** [comment]
名称については全体的に見直します。

**Comment by reachscript-jak** [comment]
goodだと思います！！👏

**Comment by macmeals** [comment]
ご確認ありがとうございます👏こちらもクローズさせて頂きます。
