### ISSUE TITLE
componentフォルダ配下について

### ISSUE THREAD

**Issue by reachscript-jak** [macmeals/todo_react_app3#8]
componentフォルダ配下にページの役割を担うコンポーネントと、各種細かいコンポーネントが同階層になっているので、ページ系のコンポーネント（routerファイルに記述するようなコンポーネント）に関してはcomponent > pages等のフォルダを作成し格納すると見通しが良くなるかと思います！

**Comment by macmeals** [comment]
ページ系のコンポーネント（以下５つ）
　・Page404.jsx
　・TodoList.jsx
　・TodoRegister.jsx
　・TodoUpdate.jsx
　・TopPage .jsx

こちらをcomponetフォルダにPageフォルダを新設し、そちらに格納しました。

**Comment by macmeals** [comment]
合わせてRouteのコンポーネントのパスも修正しました。

**Comment by reachscript-jak** [comment]
👍👍👍

**Comment by macmeals** [comment]
ご確認ありがとうございます。こちらクローズさせていただきます！
